keys:
  - &luxus age1ncepfcrzfep624tpanhqfflafznh7ftuqffv0nfq24jhv3dwx40sltjkad
  - &vanessa age1ncepfcrzfep624tpanhqfflafznh7ftuqffv0nfq24jhv3dwx40sltjkad
  - &laptop 044563484de3f8a04eab2fa2a1f1884c176b12c3
  - &work 1d848bac4d07e12426f76ce9eac9bb416ff96587

creation_rules:
  - path_regex: hosts/vanessa/restic-vanessa.yaml
    key_groups:
      - age:
        - *luxus
        - *vanessa
  - path_regex: hosts/laptop/restic-laptop.yaml
    key_groups:
      - pgp:
        - *bbigras
        - *laptop
