# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=home" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=persist" ];
      neededForBoot = true;
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd"  "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=log" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/86C4-06EB";
      fsType = "vfat";
    };

  fileSystems."/mnt/btr_pool" =
    { device = "/dev/disk/by-uuid/443b5b30-750a-4501-85b8-6655ecd4f499";
      fsType = "btrfs";
      options = [
        "subvolid=5"
        # "compress=zstd"
        "noatime"
      ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
